### PR TITLE
Add gitignore and velocityWorldSetpoint

### PR DESCRIPTION
**Pull request by Zhenghao-Dai**
Implement #8

### CODE REVIEW

**Comment by jpreiss** [comment]
@whoenig can you take a look at this? We are trying to add support in `crazyflie_ros` and `pycrazyswarm` too, it starts to get complicated with the forks and submodule dependencies.

**Comment by whoenig** [comment]
This looks great - Thanks! And sorry for the delay.

**Comment by jpreiss** [comment]
No problem! Hope RSS went smoothly :)

Can you also update the submodule version in `crazyflie_ros`? We will have a pull request for that and `pycrazyswarm` too, probably after real hardware testing.

BTW, I noticed the `crazyflie_cpp` submodule version is already different in `crazyflie_ros` and `crazyflie_tools` - not sure if that's intentional or not.

**Comment by whoenig** [comment]
Submodules in `crazyflie_ros` are updated now. The differences are not intentional, but usually I only pull an update if I actually need the code changes in the ROS or tools layer (which in case of new features makes sense, but for bugfixes can be bad.)

**Comment by jpreiss** [comment]
Thanks!

@Zhenghao-Dai you should now be able to do a fresh fork of `crazyflie_ros` and copy your `crazyflie_driver` updates there.

**Pull request merged**
